### ISSUE TITLE
Archivo test.py

### ISSUE THREAD

**Issue by Siaper** [ejdecena/proyecto_calculo#1]
Buenas profe, dentro del archivo test.py ¿nosotros tenemos que dejarle un codigo donde se pruebe la funcion que hicimos o uste se va a encargar de eso?

**Comment by ejdecena** [comment]
Hola. No, el archivo `test.py` es un programa que va a **probar todas las funciones que ustedes codifiquen**, yo debo programarlo en las próximas horas, así que procuren ustedes mismos probar sus funciones y que den los resultados exactos, porque el programa que corrige es implacable: **califica con cero o diez cada función**, según si da o no da el resultado exacto.

**Comment by Siaper** [comment]
Ok muchas gracias profe
